Repository openshift/ci-chat-bot, pull requests merged in 2020-02, with the labels that each got.

#59 Change how we calculate launched clusters, wait longer
  manager.go
  prow.go
Labels: approved, lgtm, size/XS

#60 Detect namespaces missing and exit early
  prow.go
Labels: approved, lgtm, size/M

#61 Revert changes to detect namespace deletion, races with creation
  prow.go
Labels: approved, lgtm, size/XS

#62 Don't resync jobs that are in a terminal phase
  manager.go
Labels: approved, lgtm

#64 During setup, attempt to set the `BRANCH` variable
  manager.go
  pkg/prow/prow.go
  prow.go
Labels: approved, lgtm, size/M

#65 Update default versions after branching
  manager.go
Labels: approved, lgtm, size/XS

#63 Add preserve_bootstrap variant
  prow.go
Labels: approved, lgtm, size/XS
