Repository openshift/ci-chat-bot, pull requests merged in 2020-03, with the labels that each got.

#66 Alow multiple PRs to be specified for a given launch command
  go.sum
  manager.go
  pkg/prow/prow.go
  prow.go
  slack.go
Labels: approved, lgtm, size/XL

#68 Return clearer error message when `build` is given without args
  slack.go
Labels: approved, lgtm, size/XS

#70 Grant all authenticated users access to the images from build
  prow.go
Labels: approved, lgtm, size/S

#71 Clear tests from child builds on PRs to reduce potential for accidents
  prow.go
Labels: approved, lgtm, size/XS

#72 Increase quota for jobs
  manager.go
  prow.go
Labels: approved, lgtm, size/S

#73 github: send a user-agent header for identification
  .gitignore
  manager.go
Labels: approved, lgtm

#74 Detect sub job failures correctly
  prow.go
Labels: approved, lgtm

#75 Ensure tag_specification has a cluster set
  go.mod
  go.sum
  prow.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: approved, lgtm
