Repository openshift/ci-chat-bot, pull requests merged in 2022-11, with the labels that each got.

#312 add router&handler for events + refactoring
  eventHandler.go
  go.mod
  go.sum
  main.go
  pkg/manager/manager.go
  pkg/manager/prow.go
  pkg/manager/types.go
  pkg/prow/prow.go
  pkg/slack/actions.go
  pkg/slack/events/handler.go
  pkg/slack/events/messages/message-handler.go
  pkg/slack/events/router/router.go
  pkg/slack/parser/commandParser.go
  pkg/slack/parser/types.go
  pkg/slack/slack.go
  pkg/utils/utils.go
  slack.go
  slack_test.go
  vendor/github.com/sbstjn/allot/.gitignore
  vendor/github.com/sbstjn/allot/LICENSE.md
  vendor/github.com/sbstjn/allot/Makefile
  vendor/github.com/sbstjn/allot/README.md
  vendor/github.com/sbstjn/allot/circle.yml
  vendor/github.com/sbstjn/allot/command.go
  vendor/github.com/sbstjn/allot/match.go
  vendor/github.com/sbstjn/allot/parameter.go
  vendor/github.com/sbstjn/hanu/.codeclimate.yml
  vendor/github.com/sbstjn/hanu/.gitignore
  vendor/github.com/sbstjn/hanu/Gopkg.lock
  vendor/github.com/sbstjn/hanu/Gopkg.toml
  vendor/github.com/sbstjn/hanu/LICENSE.md
  vendor/github.com/sbstjn/hanu/Makefile
  vendor/github.com/sbstjn/hanu/README.md
  vendor/github.com/sbstjn/hanu/command.go
  vendor/github.com/sbstjn/hanu/conversation.go
  vendor/github.com/sbstjn/hanu/main.go
  vendor/github.com/sbstjn/hanu/message.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: lgtm, approved, tide/merge-method-squash

#314 manager: use first bundle from multi-bundle config
  pkg/manager/manager.go
  pkg/manager/prow.go
  pkg/manager/types.go
Labels: lgtm, approved

#313 add a modal for creating Jira bugs
  go.mod
  main.go
  pkg/jira/jira.go
  pkg/slack/interactions/handler.go
  pkg/slack/interactions/router/router.go
  pkg/slack/modals/bug/view.go
  pkg/slack/modals/handlers.go
  pkg/slack/modals/helpdesk/view.go
  pkg/slack/modals/register.go
  pkg/utils/utils.go
  slack.go
Labels: lgtm, approved

#315 manager: build optional images
  pkg/manager/manager.go
  pkg/manager/prow.go
Labels: lgtm, approved

#317 bugfix on multistageNameFromParams params check
  pkg/manager/manager.go
Labels: lgtm, approved

#318 manager: move check for empty variants
  pkg/manager/manager.go
Labels: lgtm, approved

#319 Remove support for template jobs
  go.mod
  go.sum
  main.go
  pkg/manager/manager.go
  pkg/manager/prow.go
  pkg/manager/types.go
  pkg/slack/slack.go
  vendor/github.com/moby/spdystream/CONTRIBUTING.md
  vendor/github.com/moby/spdystream/LICENSE
  vendor/github.com/moby/spdystream/MAINTAINERS
  vendor/github.com/moby/spdystream/NOTICE
  vendor/github.com/moby/spdystream/README.md
  vendor/github.com/moby/spdystream/connection.go
  vendor/github.com/moby/spdystream/handlers.go
  vendor/github.com/moby/spdystream/priority.go
  vendor/github.com/moby/spdystream/spdy/dictionary.go
  vendor/github.com/moby/spdystream/spdy/read.go
  vendor/github.com/moby/spdystream/spdy/types.go
  vendor/github.com/moby/spdystream/spdy/write.go
  vendor/github.com/moby/spdystream/stream.go
  vendor/github.com/moby/spdystream/utils.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/modules.txt
Labels: lgtm, approved

#321 .ci-operator.yaml: add file
  .ci-operator.yaml
Labels: lgtm, approved

#322 Makefile: use openshift machinery
  Makefile
  cmd/ci-chat-bot/main.go
  cmd/ci-chat-bot/slack.go
  go.mod
  go.sum
  hack/tools.go
  pkg/version/version.go
  vendor/github.com/openshift/build-machinery-go/.ci-operator.yaml
  vendor/github.com/openshift/build-machinery-go/LICENSE
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/doc.go
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/default.mk
  vendor/github.com/openshift/build-machinery-go/make/doc.go
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/doc.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/tmp.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/help.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/github.com/openshift/build-machinery-go/scripts/doc.go
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/github.com/openshift/build-machinery-go/scripts/update-deps.sh
  vendor/modules.txt
Labels: lgtm, approved

#323 hack/linter.sh: remove old linter
  Makefile
  hack/linter.sh
Labels: lgtm, approved

#324 bump test-infra to revision dfec9ce18ddd3133a675759e61f11befa735c428
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/git/v2/remote.go
  vendor/modules.txt
Labels: lgtm, approved

#320 Update FAQ with Bare-Metal access instruction
  docs/FAQ.md
Labels: lgtm, approved, ok-to-test

#325 pkg/manager/prow: add hypershift-hosted platform
  pkg/manager/prow.go
Labels: lgtm, approved
